@baseUrl = https://simracing-api.onrender.com
@token = TOKEN_HERE
@userId = ID_HERE
@teamId = TEAM_ID_HERE
@raceId = RACE_ID_HERE

### REGISTER
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "Batiste",
    "email": "batiste@email.com",
    "password": "test123"
}

###

### LOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "batiste@email.com",
    "password": "test123"
}

###

### ME
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}

---

### USERS

### GET ALL
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

###

### GET BY ID
GET {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}

###

### CREATE
POST {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Max Verstappen",
 "email": "max@f1.com",
 "password": "123456"
}

###

### UPDATE
PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Updated name"
}

###

### DELETE
DELETE {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{token}}

---

### TEAMS

### GET ALL
GET {{baseUrl}}/api/teams
Authorization: Bearer {{token}}

###

### CREATE
POST {{baseUrl}}/api/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Red Bull Racing",
 "country": "Austria"
}

###

### GET BY ID
GET {{baseUrl}}/api/teams/{{teamId}}
Authorization: Bearer {{token}}

###

### UPDATE
PUT {{baseUrl}}/api/teams/{{teamId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Updated Team"
}

###

### DELETE
DELETE {{baseUrl}}/api/teams/{{teamId}}
Authorization: Bearer {{token}}

---

### RACES

### GET ALL
GET {{baseUrl}}/api/races
Authorization: Bearer {{token}}

###

### CREATE
POST {{baseUrl}}/api/races
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Spa GP",
 "track": "Spa-Francorchamps",
 "date": "2026-04-01",
 "team": "{{teamId}}"
}

###

### GET BY ID
GET {{baseUrl}}/api/races/{{raceId}}
Authorization: Bearer {{token}}

###

### UPDATE
PUT {{baseUrl}}/api/races/{{raceId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "name": "Updated Race"
}

###

### DELETE
DELETE {{baseUrl}}/api/races/{{raceId}}
Authorization: Bearer {{token}}